name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      - name: Crear archivo de credenciales
        run: |
          echo "[credentials]" > credentials.ini
          echo "user=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini

      - name: Build docker image
        run: docker build -t devops_ws:$(date +%s) .
